# Generated by Django 4.1.7 on 2023-04-03 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_tipoproduto_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
