# Generated by Django 4.1.7 on 2023-04-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_delete_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
