# Generated by Django 4.1.7 on 2023-04-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='tipoproduto',
            new_name='fktipoproduto',
        ),
    ]
